### ISSUE TITLE
 Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag

### ISSUE THREAD

**Issue by yuwade** [alipay/alipay-sdk-nodejs#19]
{ Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at Sign.sign (internal/crypto/sig.js:83:26)
    at Object.sign (d:\WorkPlace\nodes\node_modules\alipay-sdk\lib\util.js:49:34)
    at AlipaySdk.exec (d:\WorkPlace\nodes\node_modules\alipay-sdk\lib\alipay.js:224:33)
    at run (d:\WorkPlace\nodes\alipay\index.js:58:36)
    at Object.<anonymous> (d:\WorkPlace\nodes\alipay\index.js:73:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
  opensslErrorStack:
   [ 'error:04093004:rsa routines:old_rsa_priv_decode:RSA lib',
     'error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error',
     'error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error' ] }

**Comment by tudou527** [comment]
看起来是你设置的秘钥有问题，比如格式。可以按这个 [文档](https://github.com/alipay/alipay-sdk-nodejs#%E6%94%AF%E4%BB%98%E5%AE%9D%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E9%85%8D%E7%BD%AE) 检查一下，不行的话可以发一份可复现的代码到我邮箱 tudou527#gmail.com
